version: "3"
services:
    app:
        build: .
        container_name: framework
        working_dir: /var/www/html/framework
        ports: 
          - "8081:80"
        volumes:
            - ./:/var/www/html/framework
        networks:
            - app-network
    db:
        image: mysql:5.7
        container_name: banco
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        env_file:
            - ./.env
        networks:
            - app-network
networks:
    app-network:
        driver: bridge